apiVersion: v2
name: redash-mcp-server
description: A Helm chart for Redash MCP Server
type: application
version: 0.1.0
appVersion: "0.1"
keywords:
  - mcp
  - redash
  - model-context-protocol
maintainers:
  - name: jonico

